# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{autolink}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Burke Libbey"]
  s.date = %q{2010-08-25}
  s.description = %q{By setting a default lineage in each model, and using these monkeypatches to Rails, the url helpers are able to generate complex urls from a single ActiveRecord::Base object. Works in 2.3.8, probably other 2.3 railses.}
  s.email = %q{burke@burkelibbey.org}
  s.files = [
    "lib/autolink.rb",
     "lib/autolink/action_controller_extensions.rb",
     "lib/autolink/action_view_extensions.rb",
     "lib/autolink/rspec.rb",
     "spec/spec_helper.rb",
     "spec/spec_opts.rb"
  ]
  s.homepage = %q{http://github.com/burke/autolink}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Automatically generate nested paths in Rails 2.3 according to your application's setup}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

